### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by joecohens** [dinkbit/epoch#1]
[https://twitter.com/wesbos/status/955833868636098565](https://twitter.com/wesbos/status/955833868636098565)

- [x] S and MS Timestamp to Date
- [x] Date Picker to S and MS timestamp
- [x] Display current, live timestamp 
- [x] Ability to pick timezone
- [x] Readable dates for everything
- [x] Ability to add time. eg: Now + 3 Hours

**Comment by joecohens** [comment]
Done in https://github.com/dinkbit/epoch/pull/5
